### ISSUE TITLE
首页home - 需要提供的材料

### ISSUE THREAD

**Issue by Vickysir** [Vickysir/website-ccba#1]
- 【关于我们】展示的文字，图片
<img width="1598" alt="image" src="https://user-images.githubusercontent.com/29813234/220152144-1cec6e81-d710-4e6a-96ca-c659b0e94a3c.png">

- 【口号展示】
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/29813234/220152237-1eef6dd8-5c0f-438b-9d6c-5f31b2deee74.png">

- 【外部链接】展示的图片
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/29813234/220152346-5dfc528f-49b5-4dab-8f57-054b53ae9cc9.png">

**Comment by lee197** [comment]
关于我们： 
了解更多这个按钮，稍微扁一点靠下一点

**Comment by lee197** [comment]
关于我们:
图片 
![li-yang-5h_dMuX_7RE-unsplash](https://user-images.githubusercontent.com/11969113/220200460-b43aad8b-b0ba-4faa-a5c9-ae22ed81e7f8.jpg)

**Comment by lee197** [comment]
新闻需要做成两排，上面四个，下面四个。 我先给他们看看效果，不行的话可能按照以前的方案。

**Comment by lee197** [comment]
合作伙伴：
能否麻烦你去这里，点击五个网站（很多国内网站我打不开），找到并下载他们的logo，然后放到我们的网站上。

<img width="972" alt="Screenshot 2023-02-22 at 18 28 55" src="https://user-images.githubusercontent.com/11969113/220723035-b3733106-819e-4871-8af7-ae38d856db02.png">

样式就跟我们网站样式一致，白底，再配上logo
