### ISSUE TITLE
enterprise企业分类

### ISSUE THREAD

**Issue by Vickysir** [Vickysir/website-ccba#2]
按这些tab分类： 餐饮，酒店，信息技术，其他，分别对应的企业为？请列举出正确分类？

**Comment by lee197** [comment]
酒店： The Kingsley Hotel （金斯利酒店）， Fota Island Resort

**Comment by lee197** [comment]
餐馆：Fudi&More, Wasabi sushi, Miyazaki Japanese, Sakura cusine, The Great Wall, Yuan Ming Yuan

**Comment by lee197** [comment]
我问他们要资料，他们拖得比较慢。 
要不这样吧，你就去原来的网站，每个分类随机找6个企业，配上他们的图片，先放上。我给他们看看效果，到时候再改
